server:
  port: 8765

spring:
  application:
    name: service-feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Feign自带断路器但是默认关闭，需要在配置文件中手动开启断路器功能
feign:
  hystrix:
    enabled: true